/**
 * A piece: music written, played and recorded in jam (jam.phareim.no), the
 * radio's sister instrument. The same engine plays it: the piece conductor
 * (piece/conductor.ts) turns it into BarPlans for the radio's player.
 *
 * A piece is a loop of 1–4 phrases of 8 bars. Harmony is one progression
 * per phrase in the radio's chord-token grammar; every track keeps one short
 * string per bar of the loop. That keeps a whole piece a few kilobytes of
 * text that Opus reads and writes directly.
 *
 * Bar notation
 *
 * Note bars (tracks with a `voice`): space-separated events
 *   <step>:<pitches>:<len>[:<vel>]
 *   step     sixteenth the note starts on, 0 ≤ step < 16; decimals allowed
 *            (at most 2 places) for triplets and unquantized playing
 *   pitches  note names joined by '+', e.g. C4, Eb3, F#5, C4+E4+G4
 *            (C4 = MIDI 60; sharps '#', flats 'b'; octave −1..9)
 *   len      length in sixteenths, > 0, decimals allowed; may run past the
 *            end of the bar (the note keeps sounding into the next bar)
 *   vel      velocity 1..9 (vel / 9), default 7
 *   Example: "0:C3+G3:8 8:E3:4:5 12:D3:2 14.5:B2:1.5:4"
 *
 * Drum bars (tracks with a `kit`): space-separated <hit>:<16 chars>, the
 * radio's groove strings: '.' rest, 'x' hit, 'X' accent, 'g' ghost, and
 * '-' (only after a 'z' riser) hold. Hits: k s c h o r p t m T x z (see
 * DrumHit in ../types.ts).
 *   Example: "k:x.......x.x..... s:....X.......X... h:x.x.x.x.x.x.x.x."
 *
 * An empty string is an empty bar.
 */
import type { AmbienceId, FxSpec, KitId, Layer, Mode, VoiceId } from '../types.ts'

export const PIECE_VERSION = 1
export const PIECE_PHRASE_BARS = 8

export type Level = 0 | 1 | 2 | 3 | 4

/** Where a track's bars came from. */
export type TrackSource =
  | 'played'   // recorded from an instrument
  | 'written'  // entered in the step editor
  | 'library'  // a stored pattern or snippet
  | 'grown'    // generated by the radio's composer (piece/grow.ts)
  | 'opus'     // written by Opus on request

/** Which on-screen instrument plays a track live (the UI's choice; the sound is `voice`/`kit`). */
export type Instrument = 'piano' | 'guitar' | 'bass' | 'drums' | 'touch'

export interface Track {
  /** Unique within the piece: [A-Za-z0-9_-]{1,32}. */
  id: string
  name: string
  /** The mixer bus and the musical role (the radio's layers). */
  layer: Layer
  /** Exactly one of voice (note bars) and kit (drum bars). */
  voice?: VoiceId
  kit?: KitId
  instrument?: Instrument
  /** The track plays at this intensity and above: the piece's ladder. */
  enter: Level
  /** 0..1.5, scales velocity. Default 1. */
  gain?: number
  mute?: boolean
  solo?: boolean
  source: TrackSource
  /** One bar string per bar of the loop: `phrases * 8` entries. */
  bars: string[]
}

/** The "what does this feel like" conversation, and the brief it ends in. */
export interface Feel {
  messages: Array<{ role: 'petter' | 'opus'; text: string; at?: string }>
  /** A short description of the place and mood, for a channel's name, blurb and painted scene. */
  brief: string
}

export interface Piece {
  v: 1
  /** [A-Za-z0-9_-]{1,40}; the client makes it (e.g. 'p-3f9a2c'). */
  id: string
  name: string
  /** Pitch class of home, 0..11 (C = 0). */
  tonic: number
  mode: Mode
  /** 50..200. */
  bpm: number
  /** 0..0.5 of a sixteenth. */
  swing: number
  /** Loop length in phrases of 8 bars. */
  phrases: 1 | 2 | 3 | 4
  /**
   * One progression per phrase, in the radio's chord-token grammar
   * (Progression in ../types.ts); each must last exactly 8 bars with
   * `chordBars` bars per token unless a token carries ':n'.
   */
  chords: string[]
  /** Default bars per chord token: 1 or 2 (default 2). */
  chordBars?: 1 | 2
  tracks: Track[]
  /** The intensity the piece was left at. */
  intensity: Level
  /**
   * The radio landscape it sounds from: effects, ambience, voices and the
   * intensity ladder that growing follows. Any landscape id the lookup
   * knows (built-in or composed).
   */
  base?: string
  /** Overrides of the base's effects. */
  fx?: Partial<FxSpec>
  /** Ambience textures and levels; replaces the base's when set. */
  ambience?: Partial<Record<AmbienceId, number>>
  feel?: Feel
  /** The radio channel (landscape id) made from this piece, once made. */
  channel?: string
}

/** A parsed note from a note bar. */
export interface PieceNote {
  step: number
  midi: number
  len: number
  /** 0..1 */
  vel: number
}
